services:
  db:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongodb
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_HOST: db  # Use service name for internal connection
      MONGODB_HOST: mongodb  # Use service name for internal connection
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ":6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  app_network:
    driver: bridge