# Generated by Django 5.2 on 2025-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birthdate',
            field=models.DateField(default='2004-11-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(default='Россия', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='sex',
            field=models.CharField(default='М', max_length=1),
            preserve_default=False,
        ),
    ]
